export let options = [
  { "id": 1, "label": "Flour", "value": "Flour" },
  { "id": 2, "label": "Eggs", "value": "Eggs" },
  { "id": 3, "label": "Milk", "value": "Milk" },
  { "id": 4, "label": "Sugar", "value": "Sugar" },
  { "id": 5, "label": "Butter", "value": "Butter" },
  { "id": 6, "label": "Salt", "value": "Salt" },
  { "id": 7, "label": "Yeast", "value": "Yeast" },
  { "id": 8, "label": "Baking powder", "value": "Baking_Powder" },
  { "id": 9, "label": "Chocolate chips", "value": "Chocolate_Chips" },
  { "id": 10, "label": "Vanilla extract", "value": "Vanilla_Extract" },
  { "id": 11, "label": "Ghee", "value": "Ghee" },
  { "id": 12, "label": "Mustard oil", "value": "Mustard_Oil" },
  { "id": 13, "label": "Turmeric powder", "value": "Turmeric_Powder" },
  { "id": 14, "label": "Chili powder", "value": "Chili_Powder" },
  { "id": 15, "label": "Cumin seeds", "value": "Cumin_Seeds" },
  { "id": 16, "label": "Coriander seeds", "value": "Coriander_Seeds" },
  { "id": 17, "label": "Garlic", "value": "Garlic" },
  { "id": 18, "label": "Ginger", "value": "Ginger" },
  { "id": 19, "label": "Onions", "value": "Onions" },
  { "id": 20, "label": "Tomatoes", "value": "Tomatoes" },
  { "id": 21, "label": "Potatoes", "value": "Potatoes" },
  { "id": 22, "label": "Chickpeas", "value": "Chickpeas" },
  { "id": 23, "label": "Lentils", "value": "Lentils" },
  { "id": 24, "label": "Rice", "value": "Rice" },
  { "id": 25, "label": "Fish", "value": "Fish" },
  { "id": 26, "label": "Chicken", "value": "Chicken" },
  { "id": 27, "label": "Beef", "value": "Beef" },
  { "id": 28, "label": "Yogurt", "value": "Yogurt" },
  { "id": 29, "label": "Lime juice", "value": "Lime_Juice" },
  { "id": 30, "label": "Coconut milk", "value": "Coconut_Milk" },
  { "id": 31, "label": "Bananas", "value": "Bananas" },
  { "id": 32, "label": "Mangoes", "value": "Mangoes" },
  { "id": 33, "label": "Panch Phoron", "value": "Panch_Phoron" },
  { "id": 34, "label": "Bay leaves", "value": "Bay_Leaves" },
  { "id": 35, "label": "Green chilies", "value": "Green_Chilies" },
  { "id": 36, "label": "Cilantro", "value": "Cilantro" },
  { "id": 37, "label": "Mint leaves", "value": "Mint_Leaves" },
  { "id": 38, "label": "Shrimp", "value": "Shrimp" },
  { "id": 39, "label": "Hilsa fish", "value": "Hilsa_Fish" },
  { "id": 40, "label": "Begun", "value": "Begun" },
  { "id": 41, "label": "Aloo", "value": "Aloo" },
  { "id": 42, "label": "Doi", "value": "Doi" }
];
