import { Inter } from 'next/font/google'
import './globals.css'
import Nabvar from './component/Nabvar'
import Porividers from './Providers'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Next Recipe',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
<Porividers>
  <Nabvar></Nabvar>
<div>{children}</div>
</Porividers>


      </body>
    </html>
  )
}
